yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "@chakra-ui/theme@*":
    dependencies:
      "@chakra-ui/styled-system": "*"
  "@chakra-ui/menu@*":
    dependencies:
      "@popperjs/core": "*"
  "@chakra-ui/accordion@1.3.3":
    peerDependencies:
      framer-motion: "*"
  "@chakra-ui/skeleton@1.1.15":
    peerDependencies:
      "@chakra-ui/theme": "*"
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/switch@1.2.6":
    peerDependencies:
      framer-motion: "*"
  "redoc@2.0.0-rc.54":
    dependencies:
      call-me-maybe: "^1.0.1"
      fast-safe-stringify: "^1.2.3"
